Sprint 12: group project
fatco321/java-filmorate pull request #16
Opened 2022-08-21 19:40 UTC by 350StealthDelta

Add features form task branches:
1. add-director
2. add-common-films
3. add-most-populars
4. add-reviews
5. add-recommendations
6. add-feed
7. add-search

2022-08-22 20:47 UTC, Fleaman777 requested changes
Ребята привет.

Поздравляю вас с завершением такой масштабной работы. Вы большие молодцы.
Мне очень понравилась ваша работа, видно что проделан большой путь, и однозначно, небезрезультатный. Замечаний почти нет, т.к. все сделано на высшем уровне, а те, что есть, совсем некритичные.
Что мог бы отметить отдельно: здоровские запросы, составлены грамотно и оптимально, на достойном уровене. Логика в сервисах, тоже на отлично, вопросов практически не вызывает, так же как и контроллеры.
Так держать 💪🏼

2022-08-22 20:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(value = "count", defaultValue = "10", required = false) int count,
на сколько я помню, если название аргумента совпадает с названием параметра, то явно value можно не задавать 

если это так, то value можно удалить в тех местах, где это будет актуально

2022-08-22 20:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceDb.java
> +                .build()
отличное применение билдера, 
когда в объект нужно просетать много полей

2022-08-22 20:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationsService.java
> +        }
хорошо было бы эту логику сделать через stream

2022-08-22 20:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewsServiceDB.java
> +                .build());
собирание feedDao можно было бы вынести в отдельный вспомогательный метод, и применять его в похожих местах

2022-08-22 20:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewsServiceDB.java
> +        }
optional можно "расскрыть" чуть более элегантно, через его методы наподобие orElseThrow и др.

2022-08-22 20:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/reviewsstorage/database/ReviewDbStorage.java
> +                "WHERE REVIEW_ID = ?";
этот запрос (и др. похожие) можно сделать в одном стиле с остальным(ключевые слова select, set и пр. в нижнем регистре, названия таблиц в верхнем)

2022-08-22 20:47 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/userstorage/database/RecommendationsDao.java
> +                "limit 1;";
очень круто зпрос, молодцы!

2022-08-23 19:06 UTC, 350StealthDelta commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(value = "count", defaultValue = "10", required = false) int count,
Исправили

2022-08-23 19:07 UTC, 350StealthDelta commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceDb.java
> +                .build()
Спасибо )

2022-08-23 19:07 UTC, 350StealthDelta commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationsService.java
> +        }
Сделали

2022-08-23 19:08 UTC, 350StealthDelta commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewsServiceDB.java
> +                .build());
Сделали отдельный метод в FeedDoa для этого

2022-08-23 19:08 UTC, 350StealthDelta commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewsServiceDB.java
> +        }
Сделали. Не знаю, на сколько элегантно, но теперь через возможности Optional ))

2022-08-23 19:08 UTC, 350StealthDelta commented on src/main/java/ru/yandex/practicum/filmorate/storage/reviewsstorage/database/ReviewDbStorage.java
> +                "WHERE REVIEW_ID = ?";
Сделали

2022-08-23 19:09 UTC, 350StealthDelta commented on src/main/java/ru/yandex/practicum/filmorate/storage/userstorage/database/RecommendationsDao.java
> +                "limit 1;";
Спасибо! У нас в команде есть спецы по запросам :)

2022-08-24 16:21 UTC, Fleaman777 requested changes
Отличные исправления, молодцы!
Но есть еще немного моментов которые можно поправить. Финиш близко! :)

2022-08-24 16:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationsService.java
> +        recommendedFilms = recommendedFilmIds.stream().map(filmStorage::findFilmById).collect(Collectors.toList());
что бы еще стрим хорошо воспринимался, его можно сделать в его формате: 
каждый метод на своей строке

2022-08-24 16:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/reviewsstorage/database/ReviewDbStorage.java
> +                "where REVIEW_ID = ?";
отлично,
еще можно названия столбцов и таблцы сделать в нижнем регистре

2022-08-24 16:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/userstorage/database/RecommendationsDao.java
> +                "limit 1;";
еще нужно немного улучшить запрос, что бы он имел максимум только 1 подзапрос

2022-08-25 05:53 UTC, 350StealthDelta commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationsService.java
> +        recommendedFilms = recommendedFilmIds.stream().map(filmStorage::findFilmById).collect(Collectors.toList());
Исправили

2022-08-25 05:53 UTC, 350StealthDelta commented on src/main/java/ru/yandex/practicum/filmorate/storage/reviewsstorage/database/ReviewDbStorage.java
> +                "where REVIEW_ID = ?";
Исправили

2022-08-25 05:53 UTC, 350StealthDelta commented on src/main/java/ru/yandex/practicum/filmorate/storage/userstorage/database/RecommendationsDao.java
> +                "limit 1;";
Исправили

2022-08-25 21:12 UTC, Fleaman777 approved these changes
Все здорово.
Можно еще раз однозначно сказать, вы крутые ! :)
Получено огромное количество бесценного опыта, который обязательно пригодится.
Удачи в дальнейшем обучении и в новой карьере

2022-08-25 21:12 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/userstorage/database/RecommendationsDao.java
> +                "limit 1;";
молодцы! 

ага, немного двояко получилось, сначала написал, что все круто, а потом прошу исправить.
 в 1й раз немного по другому на запрос посмотрел, упустил момент с несколькими подзапросами, 
во 2й раз уже правильно увидел, и отметил в комментарии

2022-08-25 21:12 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/reviewsstorage/database/ReviewDbStorage.java
> +                "where REVIEW_ID = ?";
Супер,

здесь наверно больше посыл был не именно исправить(хотя это тоже хорошо), а просто к информации, 

а вообще главный смысл, подобных моментов, стараться все запросы делать в одном стиле(что-то в верхнем регистре, что-то в нижнем), это что бы одинаково удобно было читать запросы в разных репозиториях

2022-08-26 06:01 UTC, fatco321 approved these changes

2022-08-26 06:03 UTC, merged