Controllers films users
fatco321/java-filmorate pull request #2
Opened 2022-07-01 20:09 UTC by fatco321

2022-07-02 15:48 UTC, kukolev requested changes

2022-07-02 15:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/JavaFilmorateApplication.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-07-02 15:48 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/JavaFilmorateApplicationTests.java
> +	@Test
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-07-02 15:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Объект LocalDate.of(1895, 12, 28) лучше сделать константой, чтобы не приходилось всякий раз создавать при валидации.

2022-07-02 15:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
Не выполнено требование ТЗ: Не реализовано логирование. Необходимо реализовать согласно ТЗ.

2022-07-02 15:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Не выполнено требование ТЗ: Не реализовано логирование. Необходимо реализовать согласно ТЗ.

2022-07-03 18:43 UTC, fatco321 commented on src/main/java/ru/yandex/practicum/filmorate/JavaFilmorateApplication.java
> +	public static void main(String[] args) {
@kukolev Добрый день! У меня все корректно отображается. Отступы сделаны без Tab.

2022-07-03 18:43 UTC, fatco321 commented on src/test/java/ru/yandex/practicum/filmorate/JavaFilmorateApplicationTests.java
> +	@Test
@kukolev У меня все корректно отображается. Отступы сделаны без Tab.

2022-07-03 18:44 UTC, fatco321 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
@kukolev Замечание исправлено.

2022-07-03 18:44 UTC, fatco321 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
@kukolev Замечание исправлено.

2022-07-03 18:44 UTC, fatco321 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
@kukolev Замечание исправлено.

2022-07-03 22:10 UTC, kukolev requested changes

2022-07-03 22:10 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/JavaFilmorateApplication.java
> +	public static void main(String[] args) {
Добрый день. Здесь таб, это видно, если попытаться выделить отступ перед словом public.

Нужно исправить.

2022-07-03 22:10 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/JavaFilmorateApplicationTests.java
> +	@Test
Добрый день. Здесь таб, это видно, если попытаться выделить отступ перед словом @Test.

Нужно исправить.

2022-07-03 22:10 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void validate(Film film) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-07-03 22:10 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void validate(User user) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-07-04 17:09 UTC, kukolev approved these changes

2022-07-04 17:09 UTC, kukolev approved these changes

2022-07-04 17:47 UTC, merged